### ISSUE TITLE
Install http://jenkins-ci.org/

### ISSUE THREAD

**Issue by yurem** [GluuFederation/ce-ubuntu#2]
We need to install Jenkins on deb-repo.gluu.org server:
1) Install latest tomcat 7.x
2) install tomcat wrapper script
3) remove all default applications from tomcat/webapps
4) put jenkins war into tomcat/webapps
5) configure jenkins to allow access only for authenticated users

**Comment by worldiswelcome** [comment]
Latest Jenkins is installed.
This is available as: https://deb-repo.gluu.org/jenkins/
