### ISSUE TITLE
Can't execute check_sssl from oxTrust corretly

### ISSUE THREAD

**Issue by yurem** [GluuFederation/ce-ubuntu#3]
We put bash version of check_ssl (https://github.com/GluuFederation/gluu-util) into chroot /ust/local/bin:

But according oxTrust logs there is error:
2015-02-13 07:53:24,443 ERROR [org.xdi.util.process.ProcessHelper] Problem during starting process check_ssl
org.apache.commons.exec.ExecuteException: Process exited with an error: 2 (Exit value: 2)

We can run check_ssl from command line without errors:
$ check_ssl
SSL_CERT CRITICAL u14.gluu.info: Cannot verify certificate\nself signed certificate|days=365;;;;

**Comment by ganesh-at-wiw** [comment]
GLUU.root@ce:~# check_ssl
SSL_CERT CRITICAL ganesh.gluu.org: Cannot verify certificate\nself signed certificate|days=365;;;;
GLUU.root@ce:~# echo $?
2
GLUU.root@ce:~#

So, essentially oxTrust is also working in same way.

**Comment by ganesh-at-wiw** [comment]
GLUU.root@ce:~# check_ssl_cert.sh -s -H `hostname`
SSL_CERT OK - X.509 self signed certificate for 'ganesh.gluu.org' from 'ganesh.gluu.org' valid until Feb 20 07:40:19 2016 GMT (expires in 365 days)|days=365;;;;
GLUU.root@ce:~# echo $?
0
GLUU.root@ce:~#


This approach can be tried if you wish.

**Comment by ganesh-at-wiw** [comment]
Now the error changed to below value after adding: "-s"  in the check_ssl command:

2015-02-20 10:22:16,276 ERROR [org.gluu.oxtrust.ldap.service.StatusCheckerTimer] check_ssl retuned an unexpected value

**Comment by ganesh-at-wiw** [comment]
The issue https://github.com/GluuFederation/oxTrust/issues/36 Will take care of this.
