### ISSUE TITLE
Install jython into chroot

### ISSUE THREAD

**Issue by yurem** [GluuFederation/ce-ubuntu#4]
We need to Install jython (without docs and examples) into /opt/jython-2.5.3 and add symbol link to /opt/jython. Also we need to add environment property to gluuTomcatWrapper.conf

There is more information in next topics:
http://ox.gluu.org/doku.php?id=oxtauth:customauthscript&s%5B%5D=jython#jython_python_integration
http://ox.gluu.org/doku.php?id=oxtauth:customauthscript&s%5B%5D=jython#jython_installation_optional

**Comment by ganesh-at-wiw** [comment]
Installed jython 2.5.3 inside chroot and committed and pushed to code in git source.
Build is going on.
Let's see if deb created works fine.

**Comment by ganesh-at-wiw** [comment]
Closing the issue. Will reopen if need be.
