### ISSUE TITLE
Optimize instructions in system_group.list system_user.list

### ISSUE THREAD

**Issue by yurem** [GluuFederation/ce-ubuntu#9]
In these files there are duplicity which can be removed.

For example:
chgrp -R adm /var/log/dmesg
chgrp -R adm /var/log/dmesg.0
chgrp -R adm /var/log/dmesg.1.gz
chgrp -R adm /var/log/dmesg.2.gz

can be replaced with
chgrp -R adm /var/log/dmesg

**Comment by adrian-gluu** [comment]
done!
